jenkins:
  systemMessage: 'Jenkins configured automatically by Jenkins Configuration as Code plugin'
  numExecutors: 2
  scmCheckoutRetryCount: 2
  mode: NORMAL
  disabledAdministrativeMonitors:
    - 'jenkins.model.InvalidBuildsDir'

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: 'admin'
          password: 'admin'

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

tool:
  nodejs:
    installations:
      - name: 'NodeJS 22'
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: '22.11.0'
                    npmPackagesRefreshHours: 72

jobs:
  - script: >
      pipelineJob('projeto-c14-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/C14-2025/food-pet.git')
                }
                branches('*/master')
                extensions { }
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

  - script: >
      pipelineJob('email-test') {
        definition {
          cps {
            script("""
              pipeline {
                agent any
                stages {
                  stage('Send Email') {
                    steps {
                      echo "Sending test mail..."
                      echo "${EMAIL_LIST}"
                      mail to: "${EMAIL_LIST}",
                           subject: "Teste de Email - Jenkins",
                           body: "Este é um e-mail de teste enviado pelo Jenkins via JCasC."
                    }
                  }
                }
              }
            """)
            sandbox()
          }
        }
      }

unclassified:
  mailer:
    smtpHost: 'smtp.gmail.com'
    smtpPort: '587'
    useSsl: false
    useTls: true
    replyToAddress: '${EMAIL_SENDER}'
    authentication:
      username: '${EMAIL_SENDER}'
      password: '${EMAIL_PASS}'

  globalLibraries:
    libraries: []

  sonarGlobalConfiguration:
    installations:
      - name: 'SonarQubeServer'
        serverUrl: 'http://sonarqube:9000'
        credentialsId: 'sonarqube-token'
